# Start in fullscreen mode by default.
fs=no

# For UOSC
osc=no
osd-bar=no
border=no
keep-open=always

#
#   HWACCELL
#
profile=high-quality
vo=gpu-next
priority=high
gpu-api=d3d11

d3d11-output-csp=srgb

gpu-context=d3d11

hwdec=auto
#hwdec=d3d11va-copy
d3d11va-zero-copy=yes

vf=d3d11vpp:scaling-mode=intel
d3d11-flip=yes
dither-depth=8
demuxer-thread=yes

vd-lavc-dr=yes
target-peak=1000
target-colorspace-hint=yes
#scale-antiring=0.6



#
#   VIDEO
#
hr-seek-framedrop=no
video-sync=audio # Some prefer having this set to display-resample

#
#   AUDIO
#
audio-exclusive=no # Enable this if you only want audio from mpv.


#
#   COLOR SETTINGS
#
target-colorspace-hint=yes
target-prim=auto # Set to your display primaries or auto
target-trc=auto # Set to your display gamma or auto
video-output-levels=full
target-peak=auto # Adjust to display peak HDR brightness.
allow-delayed-peak-detect=no
tone-mapping=auto


#
#   SCALING
#
scale=ewa_lanczossharp
dscale=mitchell
cscale=ewa_lanczossharp
deband=no                                       # Turn on only for videos with banding. (Keybind=d)
deband-iterations=2                             # https://mpv.io/manual/stable/#options-deband-iterations
deband-threshold=64                             # https://mpv.io/manual/stable/#options-deband-threshold
deband-range=17                                 # https://mpv.io/manual/stable/#options-deband-range
deband-grain=12                                 # https://mpv.io/manual/stable/#options-deband-grain


# Only use these if you have high-end hardware
# glsl-shader="~~/shaders/nnedi3-nns128-win8x4.hook"
# glsl-shader="~~/shaders/ArtCNN_C4F32.glsl"

#
#   LOGGING
#
#log-file="./mpv-enhanced-log.txt"
#msg-level="vapoursynth=trace,d3d11vpp=debug"

#
#   PROFILES
#

ytdl=yes

[rife]
vf-add=@rife:vapoursynth="C:\Users\Adnan\mpv-enhanced\portable_config\rife.vpy"
